<?php

use Fisharebest\Webtrees\I18N;

/** @var string $content */
/** @var string $title */
?>
<div class="wt-page-content">
    <?php $placeName = e($location->fullName()); ?>
    <?php $placeUrl = e($location->url()); ?>
    <h2 class="wt-page-title mb-4">
        <?= I18N::translate('External place information for %s', '<a href="' . $placeUrl . '">' . $placeName . '</a>') ?>
    </h2>
    <?= $content ?>
</div>
